## Traefik Ingress Resouce to connect to pod from web
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-{{ include "frontend.fullname" . }}
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: {{ .Values.ingressroute.host }} 
    services:
    - name: {{ include "frontend.fullname" . }} 
      port: {{ .Values.service.port }} 
    # middlewares:
    # - name: redirect-permanent