## Traefik Ingress Resouce to connect to pod from web
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https-{{ include "frontend.fullname" . }}
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: {{ .Values.ingressroute.match }} 
    services:
    - name: {{ include "frontend.fullname" . }} 
      port: {{ .Values.service.port }} 
  tls:
    secretName: frontend-crt
