apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-blog
  namespace: argocd
spec:
  destination:
    namespace: blog 
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - server-values.yaml
    path: kube-manifests/frontend
    repoURL: https://github.com/rne1223/blog
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
